steps:
# 1. Сборка Docker-образа для нашего бэкенд-сервера
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/propacondom-repo/propacondom-backend:$COMMIT_SHA', './backend']

# 2. Публикация образа в Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/propacondom-repo/propacondom-backend:$COMMIT_SHA']

# 3. Развертывание образа в Cloud Run как веб-сервис
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'propacondom-service' # Название нашего сервиса
    - '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/propacondom-repo/propacondom-backend:$COMMIT_SHA'
    - '--region=europe-west3' # Регион, который мы выбрали для Firestore
    - '--platform=managed'
    - '--allow-unauthenticated' # Разрешаем доступ из интернета